// Frontend/Mobile/components/ui/TextField.tsx
import { Text, TextInput, View, type TextInputProps } from 'react-native';

type TextFieldProps = TextInputProps & {
  label: string;
  error?: string;
  className?: string;
};

export function TextField({
  label,
  error,
  className,
  ...props
}: TextFieldProps) {
  return (
    <View className={`mb-4 ${className ?? ''}`}>
      <Text className="mb-1.5 text-sm font-medium text-ink dark:text-ink-dark">
        {label}
      </Text>
      <TextInput
        placeholderTextColor="#94A3B8"
        className={`rounded-lg border px-3 py-3 text-base text-ink dark:text-ink-dark ${
          error
            ? 'border-urgency-critical'
            : 'border-border dark:border-border-dark'
        } bg-card dark:bg-card-dark`}
        {...props}
      />
      {error ? (
        <Text className="mt-1 text-xs text-urgency-critical">{error}</Text>
      ) : null}
    </View>
  );
}

// Frontend/Web/src/components/ui/TextField.vue
<script setup lang="ts">
defineProps<{
  label: string;
  error?: string;
  modelValue: string;
  type?: string;
  autocomplete?: string;
  placeholder?: string;
  required?: boolean;
}>();

defineEmits<{
  'update:modelValue': [value: string];
}>();
</script>

<template>
  <label class="mb-4 block">
    <span class="mb-1.5 block text-sm font-medium text-ink dark:text-ink-dark">
      {{ label }}
    </span>
    <input
      :type="type ?? 'text'"
      :value="modelValue"
      :autocomplete="autocomplete"
      :placeholder="placeholder"
      :required="required"
      class="w-full rounded-lg border bg-card px-3 py-3 text-base text-ink outline-none ring-primary focus:ring-2 dark:bg-card-dark dark:text-ink-dark"
      :class="
        error
          ? 'border-urgency-critical'
          : 'border-border dark:border-border-dark'
      "
      @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
    <span v-if="error" class="mt-1 block text-xs text-urgency-critical">
      {{ error }}
    </span>
  </label>
</template>
